export { default as PathologyLayout } from "./PathologyLayout"
export { default as Navbar } from "./components/Navbar"
export { default as PathologyDashboard } from "./pages/PathologyDashboard"
export { default as PathologySettings } from "./pages/PathologySettings"
export { default as SubmitReports } from "./pages/SubmitReports"